<?php

namespace Amacabr2\TagBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository {

    /**
     * Retourne des tags pour l'auto-complétation par rapport à $q permaettant ainsi une recherhce partiel
     * @param string $q
     * @return array
     */
    public function search(string $q): array {
        return $this->createQueryBuilder('t')
            ->where('t.name LIKE :search')
            ->setParameter('search', "%" . $q . "%")
            ->getQuery()
            ->getResult();
    }

}
